server:
  port: 8080

spring:  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:    host: localhost
    database: 0
    port: 6379
    password: 
    jedis:      pool:        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
    timeout: 3000ms # 连接超时时间（毫秒）
  application:
    name: mall

mybatis:  mapper-locations:  - classpath:mapper/*.xml
  - classpath*:com/**/mapper/*.xml
  
redis:
  key:
    prefix:
      authCode: "authCode:"
    expire:
      authCode: 120 # 验证码超期时间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
  
# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4GCav8FBJ41yDenYTmjj # 访问身份验证中用到用户标识
    accessKeySecret: jR5xLe3HoRxV3ZROUkwpAjmO4QvE31 # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: ralph-test # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀